spring:

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

jwt:
  prefix: 'Bearer '
  access-token-header: Authorization
  refresh-token-header: AuthorizationRefresh
  secret: ${SECRET_KEY}
  access-token-TTL: 300
  refresh-token-TTL: 259200

cookie:
  refresh-token:
    cookie-name: Refresh
    limit-time: 259200
    accepted-url: /api/members/refresh_token
    domain: ${COOKIE_DOMAIN}
    http-only: true